version: '3'
services:
  service1:
    build: ./service1
    expose:
      - "8199"
    depends_on:
      - service2
    deploy:
      replicas: 3
    networks:
      - internal_network
    volumes:
      - ./docker_stop.sh:/app/docker_stop.sh # Need for the stop function
      - ./docker-compose.yml:/app/docker-compose.yml # Need for the stop function
      - /var/run/docker.sock:/var/run/docker.sock # Need for the stop function

  service2:
    build: ./service2
    expose:
      - "5000"
    networks:
      - internal_network

  nginx:
    image: nginx:latest
    ports:
      - "8198:8198"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/html:/usr/share/nginx/html 
    depends_on:
      - service1
    networks:
      - internal_network
      
networks:
  internal_network:
    driver: bridge